# Change these first
owner: Paidly # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Marketing Site
    url: https://meetpaidly.com
  - name: Web Application
    url: https://app.meetpaidly.com
  - name: Help & Support Site
    url: https://help.meetpaidly.com
  - name: API Endpoint
    url: $API_ENDPOINT  

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.meetpaidly.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://meetpaidly.com/images/logo_on_light.svg
  name: Paidly Status
  favicon: https://meetpaidly.com/favicon-32x32.png
  navbar:
    - title: Status
      href: /
    - title: Site
      href: https://meetpaidly.com
  themeUrl: https://meetpaidly.com/status/paidlylight.css

assignees:
  - shawncarr
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
env:
  NOTIFICATION_SLACK_STRATEGY: roundrobin
  NOTIFICATION_SLACK: true
  NOTIFICATION_SLACK_WEBHOOK: true
  NOTIFICATION_SLACK_WEBHOOK_URL: ${{ secrets.NOTIFICATION_SLACK_WEBHOOK_URL }}
  NOTIFICATION_EMAIL: true
  NOTIFICATION_EMAIL_FROM: ${{ secrets.NOTIFICATION_EMAIL_FROM }}
  NOTIFICATION_EMAIL_TO: ${{ secrets.NOTIFICATION_EMAIL_TO }}
  NOTIFICATION_EMAIL_MAILGUN: true
  NOTIFICATION_EMAIL_MAILGUN_API_KEY: ${{ secrets.NOTIFICATION_EMAIL_MAILGUN_API_KEY }}
  NOTIFICATION_EMAIL_MAILGUN_DOMAIN_NAME: ${{ secrets.NOTIFICATION_EMAIL_MAILGUN_DOMAIN_NAME }}
