# Change these first
owner: Paidly # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Marketing Site
    url: https://meetpaidly.com
  - name: Web Application
    url: https://app.meetpaidly.com
  - name: Help & Support Site
    url: https://help.meetpaidly.com
  - name: API Endpoint
    url: $API_ENDPOINT
  - name: Friends Helping Friends
    url: $FHF_USER_URL

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.meetpaidly.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://meetpaidly.com/images/logo_on_light.svg
  name: Paidly Status
  favicon: https://meetpaidly.com/favicon-32x32.png
  navbar:
    - title: Status
      href: /
    - title: Site
      href: https://meetpaidly.com
  themeUrl: https://meetpaidly.com/status/paidlylight.css
  robotsText: "User-agent: * \n Disallow: /"
  
assignees:
  - shawncarr

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
